import type { WorkspaceId } from './workspaces';

export type RoleDashboardTheme = 'default' | 'executive' | 'safety' | 'quality' | 'finance' | 'field' | 'admin';

export interface RoleDashboardMeta {
  route: string;
  title: string;
  subtitle: string;
  workspaceLabel: string;
  workspaceColor: string;
  theme: RoleDashboardTheme;
  workSectionTitle: string;
  showRecentActivity: boolean;
  showCharts: boolean;
  largeActions?: boolean;
  headerLink?: { label: string; href: string };
}

/** Per-role landing dashboard metadata — 17 Bekem personas */
export const ROLE_DASHBOARD_META: Record<string, RoleDashboardMeta> = {
  executive: {
    route: '/dashboard/executive',
    title: 'Run the Company',
    subtitle: 'Company health, decisions, and executive approvals — review and drill down only.',
    workspaceLabel: 'Executive Command',
    workspaceColor: '#F97316',
    theme: 'executive',
    workSectionTitle: 'Decisions Today',
    showRecentActivity: false,
    showCharts: true,
    headerLink: { label: 'Executive Brief', href: '/insights?tab=brief' },
  },
  coo: {
    route: '/dashboard/coo',
    title: 'Operations Command',
    subtitle: "Today's work, milestones, resources, and escalations across all sites.",
    workspaceLabel: 'COO Operations',
    workspaceColor: '#8B5CF6',
    theme: 'default',
    workSectionTitle: "Today's Work",
    showRecentActivity: false,
    showCharts: true,
    headerLink: { label: 'Mission Control', href: '/mission-control' },
  },
  project_manager: {
    route: '/dashboard/project-manager',
    title: 'Project Delivery',
    subtitle: 'Projects, milestones, BOQ, PRs, issues, daily reports, and crew allocation.',
    workspaceLabel: 'Projects',
    workspaceColor: '#3B82F6',
    theme: 'default',
    workSectionTitle: 'Things Waiting For You',
    showRecentActivity: true,
    showCharts: false,
    headerLink: { label: 'All Projects', href: '/projects' },
  },
  site_engineer: {
    route: '/dashboard/site-engineer',
    title: "Today's Site Work",
    subtitle: 'Tasks, material, equipment, crew, safety, and daily reporting.',
    workspaceLabel: 'Site Operations',
    workspaceColor: '#06B6D4',
    theme: 'field',
    workSectionTitle: "Today's Tasks",
    showRecentActivity: false,
    showCharts: false,
    largeActions: true,
    headerLink: { label: 'Project Detail', href: '/projects' },
  },
  procurement_manager: {
    route: '/dashboard/procurement',
    title: 'Procurement Pipeline',
    subtitle: 'PR → RFQ → Quotes → Compare → Award → PO → Delivery tracking.',
    workspaceLabel: 'Procurement',
    workspaceColor: '#22C55E',
    theme: 'default',
    workSectionTitle: 'Things Waiting For You',
    showRecentActivity: true,
    showCharts: false,
    headerLink: { label: 'Full Procurement', href: '/procurement' },
  },
  warehouse_manager: {
    route: '/dashboard/warehouse',
    title: 'Warehouse Operations',
    subtitle: "Today's GRN, material issues, low stock, and warehouse capacity.",
    workspaceLabel: 'Warehouse',
    workspaceColor: '#22C55E',
    theme: 'default',
    workSectionTitle: 'Things Waiting For You',
    showRecentActivity: true,
    showCharts: true,
    headerLink: { label: 'Full Inventory', href: '/inventory' },
  },
  store_keeper: {
    route: '/dashboard/store-keeper',
    title: 'Store Operations',
    subtitle: 'Pending issues, dispatch, returns, and inventory.',
    workspaceLabel: 'Store',
    workspaceColor: '#84CC16',
    theme: 'field',
    workSectionTitle: 'Pending Issues',
    showRecentActivity: false,
    showCharts: false,
    largeActions: true,
    headerLink: { label: 'Inventory', href: '/inventory' },
  },
  equipment_manager: {
    route: '/dashboard/equipment',
    title: 'Equipment Command',
    subtitle: 'Machines running, idle assets, maintenance, fuel, and utilization.',
    workspaceLabel: 'Equipment & Fleet',
    workspaceColor: '#EAB308',
    theme: 'default',
    workSectionTitle: 'Things Waiting For You',
    showRecentActivity: true,
    showCharts: true,
    headerLink: { label: 'Asset Workspace', href: '/assets' },
  },
  maintenance_manager: {
    route: '/dashboard/maintenance',
    title: 'Maintenance Operations',
    subtitle: "Work orders, breakdowns, preventive service, and spare parts.",
    workspaceLabel: 'Maintenance',
    workspaceColor: '#F97316',
    theme: 'default',
    workSectionTitle: "Today's Work Orders",
    showRecentActivity: true,
    showCharts: false,
    headerLink: { label: 'Maintenance Hub', href: '/maintenance' },
  },
  safety_officer: {
    route: '/dashboard/safety',
    title: 'Safety Command',
    subtitle: 'Toolbox talks, incidents, near miss, PPE, permits, and high-risk work.',
    workspaceLabel: 'Safety',
    workspaceColor: '#EF4444',
    theme: 'safety',
    workSectionTitle: "Today's Safety Work",
    showRecentActivity: false,
    showCharts: false,
    largeActions: true,
    headerLink: { label: 'Safety Module', href: '/workforce?tab=safety' },
  },
  quality_engineer: {
    route: '/dashboard/quality',
    title: 'Quality Assurance',
    subtitle: 'Inspections, material tests, NCR, CAPA, and quality score.',
    workspaceLabel: 'Quality',
    workspaceColor: '#14B8A6',
    theme: 'quality',
    workSectionTitle: 'Inspection Queue',
    showRecentActivity: false,
    showCharts: false,
    largeActions: true,
    headerLink: { label: 'Quality Module', href: '/workforce?tab=quality' },
  },
  compliance_manager: {
    route: '/dashboard/compliance',
    title: 'Compliance Center',
    subtitle: 'Expiring licenses, renewals, government filings, contracts, and insurance.',
    workspaceLabel: 'Compliance',
    workspaceColor: '#6366F1',
    theme: 'default',
    workSectionTitle: 'Renewals Due',
    showRecentActivity: true,
    showCharts: false,
    headerLink: { label: 'Compliance+', href: '/business/compliance' },
  },
  finance_manager: {
    route: '/dashboard/finance',
    title: 'Finance Command',
    subtitle: 'Budget, committed vs actual, cash flow, payments, bills, receivables, and payables.',
    workspaceLabel: 'Finance',
    workspaceColor: '#EAB308',
    theme: 'finance',
    workSectionTitle: 'Things Waiting For You',
    showRecentActivity: true,
    showCharts: true,
    headerLink: { label: 'Business Workspace', href: '/business' },
  },
  hr_manager: {
    route: '/dashboard/hr',
    title: 'Workforce Command',
    subtitle: 'Attendance, productivity, training, certifications, skills, and allocations.',
    workspaceLabel: 'Human Resources',
    workspaceColor: '#A855F7',
    theme: 'default',
    workSectionTitle: 'Things Waiting For You',
    showRecentActivity: true,
    showCharts: false,
    headerLink: { label: 'Workforce', href: '/workforce' },
  },
  supervisor: {
    route: '/dashboard/supervisor',
    title: "Today's Site",
    subtitle: 'Crew, tasks, equipment, material, and issues on your site.',
    workspaceLabel: 'Supervisor',
    workspaceColor: '#06B6D4',
    theme: 'field',
    workSectionTitle: "Today's Work",
    showRecentActivity: false,
    showCharts: false,
    largeActions: true,
    headerLink: { label: 'Workforce', href: '/workforce' },
  },
  contractor_supervisor: {
    route: '/dashboard/contractor',
    title: 'Contractor Site',
    subtitle: 'Attendance, work output, material, and equipment for your crew.',
    workspaceLabel: 'Contractor',
    workspaceColor: '#64748B',
    theme: 'field',
    workSectionTitle: "Today's Work",
    showRecentActivity: false,
    showCharts: false,
    largeActions: true,
    headerLink: { label: 'Attendance', href: '/workforce?tab=attendance' },
  },
  org_admin: {
    route: '/dashboard/org-admin',
    title: 'Organization Admin',
    subtitle: 'Users, roles, permissions, audit, and organization settings.',
    workspaceLabel: 'Administration',
    workspaceColor: '#94A3B8',
    theme: 'admin',
    workSectionTitle: 'Admin Tasks',
    showRecentActivity: true,
    showCharts: false,
    headerLink: { label: 'Full Admin', href: '/admin' },
  },
  admin: {
    route: '/dashboard/platform-admin',
    title: 'Platform Administration',
    subtitle: 'Organizations, users, roles, permissions, audit, storage, API, and license.',
    workspaceLabel: 'Platform Admin',
    workspaceColor: '#94A3B8',
    theme: 'admin',
    workSectionTitle: 'Platform Tasks',
    showRecentActivity: true,
    showCharts: false,
    headerLink: { label: 'Admin Console', href: '/admin' },
  },
};

/** Workspaces visible in top nav per role — Phase 2 navigation filtering */
export const ROLE_VISIBLE_WORKSPACES: Record<string, WorkspaceId[]> = {
  executive: ['command', 'projects', 'assets', 'supply_chain', 'business', 'workforce', 'insights', 'integrations'],
  coo: ['command', 'projects', 'assets', 'supply_chain', 'business', 'workforce', 'insights'],
  project_manager: ['projects', 'supply_chain', 'business', 'workforce', 'insights'],
  site_engineer: ['projects', 'supply_chain', 'workforce'],
  procurement_manager: ['supply_chain', 'integrations'],
  warehouse_manager: ['supply_chain'],
  store_keeper: ['supply_chain'],
  equipment_manager: ['assets', 'integrations'],
  fleet_manager: ['assets'],
  maintenance_manager: ['assets'],
  safety_officer: ['workforce'],
  quality_engineer: ['workforce'],
  compliance_manager: ['business', 'insights'],
  finance_manager: ['business', 'insights', 'projects'],
  hr_manager: ['workforce', 'projects'],
  supervisor: ['workforce', 'projects'],
  contractor_supervisor: ['workforce'],
  org_admin: ['admin'],
  admin: ['admin', 'command', 'projects', 'assets', 'supply_chain', 'business', 'workforce', 'insights', 'integrations'],
};

export function getVisibleWorkspaces(role?: string): WorkspaceId[] | null {
  if (!role) return null;
  return ROLE_VISIBLE_WORKSPACES[role] ?? null;
}

export function getRoleDashboardMeta(role?: string): RoleDashboardMeta | null {
  if (!role) return null;
  return ROLE_DASHBOARD_META[role] ?? null;
}
